name: NASA PROJECT CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [22.x, 24.x]
        mongodb-version: ['7.0']
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: MongoDB from Github actions
        uses: supercharge/mongodb-github-action@1.12.1
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test
